const i18n={
ru:{name:'Дмитрий Гайдук',role:'Операционный директор (COO) / Исполнительный директор',dob:'14 августа 1988 • 37 лет',city:'Москва • готовность к переезду и командировкам',citizen:'Гражданство: Россия',employment:'Занятость: полная, офис',langs:'Русский (родной), English (C1)',drive:'Права A, B • личный автомобиль',navAbout:'Обо мне',navExp:'Опыт работы',navEdu:'Образование',navCourses:'Курсы',navContacts:'Контакты',download:'Скачать PDF',aboutTitle:'Обо мне',aboutText:'Эксперт с 16+ лет в управлении операционной, технической и коммерческой функциями международных компаний. Создавал подразделения с нуля, управлял командами до 1000 человек, запускал цифровые трансформации, снижал затраты и ускорял процессы. Сильные стороны: оргструктуры, CAPEX/OPEX, IT-продукты и взаимодействие с госорганами.',expTitle:'Опыт работы',eduTitle:'Образование',coursesTitle:'Курсы и дополнительное обучение',skillsTitle:'Ключевые навыки',testTitle:'Отзывы / Highlights',contactsTitle:'Контакты',contactBtn:'Связаться'},
en:{name:'Dmitrii Gaiduk',role:'COO / Executive Director',dob:'August 14, 1988 • 37 y.o.',city:'Moscow • open to relocation and travel',citizen:'Citizenship: Russia',employment:'Employment: full-time, office',langs:'Russian (native), English (C1)',drive:'Driving license A, B • own car',navAbout:'About',navExp:'Experience',navEdu:'Education',navCourses:'Courses',navContacts:'Contacts',download:'Download PDF',aboutTitle:'About Me',aboutText:'Executive with 16+ years across operations, technology and commercial leadership in international businesses. Built departments from scratch, led teams up to 1,000 people, delivered digital transformations, reduced costs and accelerated workflows. Core strengths: organizational design, CAPEX/OPEX, IT product leadership, and government relations.',expTitle:'Experience',eduTitle:'Education',coursesTitle:'Courses & Continuous Learning',skillsTitle:'Key Skills',testTitle:'Testimonials / Highlights',contactsTitle:'Contacts',contactBtn:'Contact Me'}
};
const exp=[
{cat:'auto',period:{ru:'Март 2022 — настоящее время',en:'Mar 2022 — Present'},company:'Atom (АО «Кама»)',role:{ru:'Директор департамента онлайн-сервисов',en:'Director of Online Services'},text:{ru:'Создание структуры компании (15+ отделов, 200+ человек), стратегическое и бюджетное планирование >2 млрд ₽, запуск цифровых сервисов и представительство на международных площадках.',en:'Built company structure (15+ departments, 200+ people), led strategic and budget planning over ₽2B, launched digital services and represented company at international forums.'}},
{cat:'foodtech',period:{ru:'Апр 2021 — Фев 2022',en:'Apr 2021 — Feb 2022'},company:'KFC (YUM! Russia, CIS & CEE)',role:{ru:'Руководитель внедрения технических решений',en:'Head of Technical Solutions Deployment'},text:{ru:'Разработка digital-стратегии, внедрение платформ и стандартов, управление вендорами, поддержка выхода в новые страны.',en:'Developed digital strategy, deployed platforms and standards, managed vendors, and enabled launches in new countries.'}},
{cat:'foodtech',period:{ru:'Мар 2019 — Мар 2021',en:'Mar 2019 — Mar 2021'},company:'KFC',role:{ru:'Руководитель проектного офиса',en:'Head of PMO'},text:{ru:'Управление портфелем IT-проектов, координация кросс-функциональных команд до 1000 человек, ML-платформа прогнозирования.',en:'Managed IT portfolio, coordinated cross-functional teams up to 1,000, built ML forecasting platform.'}},
{cat:'other',period:{ru:'2018 — 2010',en:'2018 — 2010'},company:'GuruTaxi • GetTaxi • System Expert • ИП • Армия • ЦПТ',role:{ru:'Консультант / Руководитель / Командир / Менеджер',en:'Consultant / Head / Commander / Manager'},text:{ru:'Оптимизация процессов и документооборота, автоматизация (20,000+ человеко-часов), 200+ гос-проектов, инженерная и управленческая экспертиза.',en:'Process optimization and digital paperwork, automation saving 20,000+ man-hours, 200+ state projects, engineering and managerial track record.'}}
];
const skills=[['Управление проектами / Project Management',95],['Оптимизация процессов / Process Optimization',94],['Бизнес-анализ / Business Analysis',90],['Бюджетирование CAPEX/OPEX',92],['Переговоры и контракт-менеджмент',89],['Управление персоналом',93],['Английский язык',84],['Оптимизация затрат',96]];
const education={ru:['Российская государственная академия интеллектуальной собственности, Москва (2010) — Экономика и менеджмент, управление ИС.'],en:['Russian State Academy of Intellectual Property, Moscow (2010) — Economics & Management, IP management.']};
const courses={ru:['Eduson Business School (2016).','30+ курсов: управление качеством, ораторское мастерство, переговоры, лидерство.'],en:['Eduson Business School (2016).','30+ courses: quality management, public speaking, negotiation, leadership.']};
const testimonials={ru:['«Дмитрий умеет переводить стратегию в результат».','«Сильный лидер изменений и культуры ответственности».'],en:['“Dmitrii turns strategy into measurable execution.”','“A transformation leader with rare operational depth.”']};

let lang='ru',filter='all';
const $=(s)=>document.querySelector(s);
const setLang=(l)=>{lang=l;document.documentElement.lang=l;document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=i18n[l][n.dataset.i18n]||n.textContent);document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));renderAll();};
const renderTimeline=()=>{const box=$('#timeline');box.innerHTML='';exp.filter(e=>filter==='all'||e.cat===filter).forEach(e=>{const a=document.createElement('article');a.className='item reveal';a.innerHTML=`<strong>${e.period[lang]}</strong><h3>${e.company}</h3><p>${e.role[lang]}</p><div class='more'><p>${e.text[lang]}</p></div><button aria-label='toggle details'>${lang==='ru'?'Подробнее':'Details'}</button>`;a.querySelector('button').onclick=()=>a.classList.toggle('open');box.appendChild(a);});observe();};
const renderAll=()=>{
 $('#educationList').innerHTML=education[lang].map(x=>`<li>${x}</li>`).join('');
 $('#coursesList').innerHTML=courses[lang].map(x=>`<li>${x}</li>`).join('');
 $('#testimonialsGrid').innerHTML=testimonials[lang].map(x=>`<blockquote>${x}</blockquote>`).join('');
 $('#skillsGrid').innerHTML=skills.map(([n,v])=>`<div class='skill-box reveal'><b>${n}</b><div class='meter'><i data-v='${v}'></i></div></div>`).join('');
 $('#quickSkills').innerHTML=skills.slice(0,4).map(([n,v])=>`<div class='q-skill'><b>${n}</b><div class='meter'><i data-v='${v}'></i></div></div>`).join('');
 renderTimeline();observe();
};
const observe=()=>{const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');const m=e.target.querySelector('.meter i');if(m)m.style.width=m.dataset.v+'%';}}),{threshold:.2});document.querySelectorAll('.reveal,.item').forEach(el=>io.observe(el));};
const renderFilters=()=>{const tags=[['all','All'],['auto','Auto'],['foodtech','Foodtech'],['other','Other']];$('#filters').innerHTML=tags.map(([id,n])=>`<button class='chip ${filter===id?'active':''}' data-id='${id}'>${n}</button>`).join('');document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{filter=c.dataset.id;renderFilters();renderTimeline();});};

$('#themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';
document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
$('#menuBtn').onclick=()=>{const s=$('#sidebar');s.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',String(s.classList.contains('open')))};
window.addEventListener('scroll',()=>{const y=window.scrollY;$('.orb-a').style.transform=`translateY(${y*.08}px)`;$('.orb-b').style.transform=`translateY(${y*.13}px)`;if(y>500)document.documentElement.dataset.theme='dark';const sections=[...document.querySelectorAll('main section')];const id=sections.findLast(s=>window.scrollY+200>=s.offsetTop)?.id;document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));});

renderFilters();setLang('ru');
