const t={en:{name:'Dmitrii Gaiduk',role:'COO / General Manager',statAge:'Age: 38',statLocation:'Location: Moscow, Russia',statExp:'Experience: 16+ years',heroTitle:'Driving Growth Through Operations, People & Technology',heroTagline:'I build resilient businesses by translating strategic goals into measurable execution.',download:'Download CV',about:'About',aboutText:'Executive operator with cross-industry track record in retail, logistics, IT and public-private programs. Led up to 1,000 people, scaled business units, and delivered digital transformations that improved speed, margin, and customer experience.',experience:'Experience',education:'Education',educationText:'MBA-level executive development in strategy, finance and organizational design. Ongoing executive education in AI-enabled operations.',skills:'Skills & KPIs',years:'years',team:'max team',projects:'transformation projects',testimonials:'Testimonials',contact:'Contacts'},ru:{name:'Дмитрий Гайдук',role:'Операционный директор / General Manager',statAge:'Возраст: 38',statLocation:'Локация: Москва, Россия',statExp:'Опыт: 16+ лет',heroTitle:'Рост бизнеса через операции, людей и технологии',heroTagline:'Создаю устойчивые бизнес-системы, превращая стратегию в измеримый результат.',download:'Скачать CV',about:'Обо мне',aboutText:'Руководитель с кросс-индустриальным опытом в ритейле, логистике, IT и проектах ГЧП. Управлял командами до 1000 человек, масштабировал направления и реализовывал цифровую трансформацию с влиянием на скорость, маржу и клиентский опыт.',experience:'Опыт',education:'Образование',educationText:'Executive-развитие уровня MBA: стратегия, финансы и оргдизайн. Непрерывное обучение в области AI и операционного управления.',skills:'Навыки и KPI',years:'лет',team:'макс. команда',projects:'проектов трансформации',testimonials:'Отзывы',contact:'Контакты'}};
const exp={en:[['2021—Present','Multi-industry Group','COO','Built unified operating model and digitized KPI governance.'],['2017—2021','Retail Network','General Manager','Scaled regional operations and lifted EBITDA through process redesign.'],['2010—2017','Telecom & IT','Operations Lead','Launched enterprise products and transformation PMO.']],ru:[['2021—н.в.','Мультиотраслевая группа','Операционный директор','Построил единую операционную модель и цифровое управление KPI.'],['2017—2021','Розничная сеть','General Manager','Масштабировал регионы и повысил EBITDA через реинжиниринг процессов.'],['2010—2017','Телеком и IT','Руководитель операций','Запустил B2B-продукты и офис трансформации.']]};
const skills={en:[['Strategic Operations',95],['Digital Transformation',92],['P&L / Budgeting',88],['Leadership & Culture',96]],ru:[['Стратегические операции',95],['Цифровая трансформация',92],['P&L / Бюджетирование',88],['Лидерство и культура',96]]};
const quotes={en:['“Dmitrii turns complexity into disciplined execution.”','“A calm leader who scales both systems and people.”','“Rare mix of commercial focus and deep operational rigor.”'],ru:['«Дмитрий превращает сложность в системное исполнение».','«Спокойный лидер, который масштабирует и системы, и людей».','«Редкое сочетание коммерческого мышления и операционной глубины».']};
const setLang=(lang)=>{document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=t[lang][n.dataset.i18n]||n.textContent);document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderExp(lang);renderSkills(lang);renderQuotes(lang)};
const renderExp=(lang)=>{const el=document.getElementById('timeline');el.innerHTML='';exp[lang].forEach((i)=>{const c=document.createElement('article');c.className='timeline-card reveal';c.innerHTML=`<strong>${i[0]}</strong><h4>${i[1]}</h4><p>${i[2]}</p><p>${i[3]}</p>`;el.appendChild(c);});observe()};
const renderSkills=(lang)=>{const el=document.getElementById('skillBars');el.innerHTML=skills[lang].map(([n,v])=>`<div class='skill reveal'><div>${n}</div><div class='bar'><i data-v='${v}'></i></div></div>`).join('');observe()};
const renderQuotes=(lang)=>{document.getElementById('quotes').innerHTML=quotes[lang].map(q=>`<blockquote class='quote reveal'>${q}</blockquote>`).join('');observe()};
const observe=()=>{const io=new IntersectionObserver((es)=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');const bar=e.target.querySelector('.bar i');if(bar) bar.style.width=bar.dataset.v+'%';}}),{threshold:.2});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));};
const animate=(id,to)=>{let v=0;const el=document.getElementById(id);const timer=setInterval(()=>{v+=Math.ceil(to/40);if(v>=to){v=to;clearInterval(timer)}el.textContent=v;},30)};
document.getElementById('themeToggle').onclick=()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==='dark'?'light':'dark'};
document.querySelectorAll('.lang-btn').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
window.addEventListener('scroll',()=>{const y=window.scrollY;document.querySelector('.layer-back').style.transform=`translateY(${y*0.15}px)`;document.querySelector('.layer-mid').style.transform=`translateY(${y*0.08}px)`;if(y>500)document.documentElement.dataset.theme='dark';});
const mobileBtn=document.querySelector('.mobile-menu-btn');mobileBtn.onclick=()=>{const s=document.querySelector('.sidebar');s.classList.toggle('open');mobileBtn.setAttribute('aria-expanded',String(s.classList.contains('open')))};
const sections=[...document.querySelectorAll('main section')];const nav=[...document.querySelectorAll('.nav-link')];window.addEventListener('scroll',()=>{const id=sections.findLast(s=>window.scrollY+180>=s.offsetTop)?.id;nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));});

document.getElementById('year').textContent=new Date().getFullYear();setLang('en');animate('expCounter',16);animate('teamCounter',1000);animate('projectsCounter',45);
